# wrangler.toml
name = "niraiya-static"
compatibility_date = "2025-10-18"
type = "javascript"

# Define your site static assets
[site]
bucket = "./dist"    # Path to your static site files

# Optional: Custom domain (replace with your own if you have one)
# [routes]
# pattern = "https://www.yourdomain.com/*"
# zone_id = "YOUR_CLOUDFLARE_ZONE_ID"
